version: '3'
volumes:
    dbase:
services:
    auth_db:
        image: mongo:3.6
        volumes: 
            - ./dbase:/db/data
    auth_app:
        build: ./app
        volumes:
            - ./app:/app
        ports:
            - 3000:3000
        depends_on: 
            - auth_db
        environment:
            APP_ENCRYPTION_KEY: '0cefd15be0fd4e0eeaf72e3656b40996'