version: '3'
networks: 
    db_subnetwork:
    queue_subnetwork:
services:
    auth_db:
        image: mongo:3.6
        volumes: 
            - ./dbase:/db/data
        networks:
            - 'db_subnetwork'
    auth_queue:
        image: redis:3.2
        networks: 
            - queue_subnetwork
    auth_app:
        build: ./app
        volumes:
            - ./app:/app
            - /app/node_modules/bcrypt/
        ports:
            - 3000:3000
        networks:
            - db_subnetwork
            - queue_subnetwork
        depends_on: 
            - auth_db
            - auth_queue
    auth_worker:
        build: ./worker
        volumes:
            - ./worker:/worker
        networks:
            - queue_subnetwork
        depends_on: 
            - auth_queue
            - auth_app
        # working_dir: /worker
        # command: ./boot.sh